import type { Source } from "./types";

export const sources: Source[] = [
  {
    id: "ea-game",
    title: "Star Wars Zero Company",
    publisher: "Electronic Arts",
    url: "https://www.ea.com/games/starwars/zero-company",
    kind: "official",
    checkedAt: "2026-08-30",
    note: "Official overview, supported platforms, story premise, Operators, Bonds, and customization.",
  },
  {
    id: "ea-faq",
    title: "Star Wars Zero Company FAQ",
    publisher: "Electronic Arts",
    url: "https://www.ea.com/games/starwars/zero-company/faq",
    kind: "official",
    checkedAt: "2026-08-30",
    note: "Official requirements, Deck status, mod support, controls, launch features, and permadeath.",
  },
  {
    id: "ea-specializations",
    title: "Specializations",
    publisher: "Electronic Arts",
    url: "https://www.ea.com/games/starwars/zero-company/specializations-hub",
    kind: "official",
    checkedAt: "2026-08-30",
    note: "Official list of eight standard Specializations and the ability model.",
  },
  {
    id: "ea-class-guide",
    title: "Specialization and Weapon Class Guide",
    publisher: "EA Help",
    url: "https://help.ea.com/id/articles/star-wars/zero-company/specialization-and-weapon-class-guide/",
    kind: "official",
    checkedAt: "2026-08-30",
    note: "Official role, ability, weapon, and playstyle guidance for each standard Specialization.",
  },
  {
    id: "ea-gameplay-overview",
    title: "Lead Zero Company to Victory",
    publisher: "Electronic Arts",
    url: "https://www.ea.com/games/starwars/zero-company/news/lead-zero-company-to-victory",
    kind: "official",
    checkedAt: "2026-08-30",
    note: "Official combat, AP, Advantage, injuries, Operators, Den, Operations, and mission overview.",
  },
  {
    id: "ea-official-video",
    title: "Star Wars Zero Company Official Gameplay Trailer",
    publisher: "EA Star Wars on YouTube",
    url: "https://www.youtube.com/watch?v=WxLUZ1omFA8",
    kind: "video",
    checkedAt: "2026-08-30",
    note: "Official video description and gameplay feature overview; no third-party claims used.",
  },
  {
    id: "steam-store",
    title: "STAR WARS Zero Company on Steam",
    publisher: "Valve / Electronic Arts",
    url: "https://store.steampowered.com/app/2075800/STAR_WARS_Zero_Company/",
    kind: "official",
    checkedAt: "2026-08-30",
    note: "Release, price, editions, languages, system requirements, features, and 53 achievements.",
  },
  {
    id: "starwars-cast",
    title: "SDCC 2026: Zero Company Cast Announcement",
    publisher: "StarWars.com",
    url: "https://www.starwars.com/news/sdcc-star-wars-zero-company-cast-announce",
    kind: "official",
    checkedAt: "2026-08-30",
    note: "Official voice cast and character background statements.",
  },
  {
    id: "ea-forums",
    title: "STAR WARS Zero Company Forum",
    publisher: "EA Forums",
    url: "https://forums.ea.com/category/star-wars-games-en/discussions/star-wars-zero-company-en",
    kind: "official",
    checkedAt: "2026-08-30",
    note: "Official community-manager issue posts and player reports; individual reports are not universal facts.",
  },
  {
    id: "steam-issue-update",
    title: "STAR WARS Zero Company Issue Updates",
    publisher: "EA Star Wars on Steam",
    url: "https://steamcommunity.com/app/2075800/discussions/0/590687864233291254/",
    kind: "official",
    checkedAt: "2026-08-30",
    note: "Developer-pinned crash, driver, CPU-threading, and Intel stability guidance.",
  },
  {
    id: "pcg-best-class",
    title: "Best Starting Class in Star Wars Zero Company",
    publisher: "PC Gamer",
    url: "https://www.pcgamer.com/games/strategy/star-wars-zero-company-best-class-specialization/",
    kind: "press",
    checkedAt: "2026-08-30",
    note: "Launch-version Scoundrel recommendation and early-game alternatives.",
  },
  {
    id: "pcg-respec",
    title: "How to Respec in Star Wars Zero Company",
    publisher: "PC Gamer",
    url: "https://www.pcgamer.com/games/strategy/star-wars-zero-company-respec-change-class/",
    kind: "press",
    checkedAt: "2026-08-30",
    note: "Cycle 3 unlock, Focus Point refunds, and named-Talent limits.",
  },
  {
    id: "mobalytics-tier",
    title: "All Specializations Ranked",
    publisher: "Mobalytics",
    url: "https://mobalytics.gg/gamebase/guides/star-wars-zero-company-specialization-tier-list",
    kind: "competitor",
    checkedAt: "2026-08-30",
    note: "One launch ranking used only as a comparison point, not copied or treated as consensus.",
  },
  {
    id: "reddit-hawks",
    title: "Best Class for Hawks Discussion",
    publisher: "r/ZeroCompany",
    url: "https://www.reddit.com/r/ZeroCompany/comments/1vxzp45/best_class_for_hawks/",
    kind: "community",
    checkedAt: "2026-08-30",
    note: "Community disagreement across Scoundrel, Medic, Gunslinger, and Scout routes.",
  },
  {
    id: "reddit-squads",
    title: "What Is Your Squad Composition?",
    publisher: "r/ZeroCompany",
    url: "https://www.reddit.com/r/ZeroCompany/comments/1w2do3c/whats_your_squad_comp/",
    kind: "community",
    checkedAt: "2026-08-30",
    note: "Early player squad patterns; small and self-selected sample.",
  },
  {
    id: "destructoid-squads",
    title: "Best Squads to Use in Star Wars Zero Company",
    publisher: "Destructoid",
    url: "https://www.destructoid.com/best-squads-to-use-in-star-wars-zero-company/",
    kind: "press",
    checkedAt: "2026-08-30",
    note: "Named-Operator squad suggestions used as one external viewpoint.",
  },
  {
    id: "allthings-chapters",
    title: "All 14 Chapters and Main Story Missions",
    publisher: "All Things How",
    url: "https://allthings.how/star-wars-zero-company-all-14-chapters-and-main-story-missions/",
    kind: "competitor",
    checkedAt: "2026-08-30",
    note: "Community chapter order cross-check; chapter guides remain gated until independently verified.",
  },
  {
    id: "whisper-hutt-debt",
    title: "In Debt to the Hutts: 80,000 Credits Guide",
    publisher: "Whisper of the House",
    url: "https://www.whisperofthehouse.com/star-wars-zero-company/in-debt-to-the-hutts-walkthrough",
    kind: "competitor",
    checkedAt: "2026-09-01",
    note: "A launch-route account covering the 80,000-Credit counter, Gorga chain, Republic Intelligence contract and Payback; retained as a route lead pending local replay.",
  },
  {
    id: "reddit-credit-economy",
    title: "Is the Credit Economy Broken?",
    publisher: "r/ZeroCompany",
    url: "https://www.reddit.com/r/ZeroCompany/comments/1w3v7as/is_it_just_me_or_is_the_credit_economy_of_this/",
    kind: "community",
    checkedAt: "2026-09-01",
    note: "Current player discussion about scarce Credits and Den or Black Market trade-offs; not direct proof of the story-debt route.",
  },
  {
    id: "allthings-achievements",
    title: "How to Unlock All 53 Achievements",
    publisher: "All Things How",
    url: "https://allthings.how/star-wars-zero-company-how-to-unlock-all-53-achievements/",
    kind: "competitor",
    checkedAt: "2026-08-30",
    note: "Category and unlock-condition cross-check; uncertain missability is labeled.",
  },
  {
    id: "pcg-review",
    title: "Star Wars Zero Company Review",
    publisher: "PC Gamer",
    url: "https://www.pcgamer.com/games/strategy/star-wars-zero-company-review/",
    kind: "press",
    checkedAt: "2026-08-30",
    note: "Full-campaign review, PC technical observations, and Steam Deck test context.",
  },
  {
    id: "pcg-linear-abilities",
    title: "Swap the Radial Ability Menu for Linear Ability Selection",
    publisher: "PC Gamer",
    url: "https://www.pcgamer.com/games/strategy/psa-swap-the-radial-ability-menu-in-star-wars-zero-company-for-more-of-a-trad-xcom-style-experience/",
    kind: "press",
    checkedAt: "2026-08-31",
    note: "Documents the Radial, Linear and Hybrid Ability Selection Style options as an input preference; provides no FPS benchmark or universal-best claim.",
  },
  {
    id: "techradar-review",
    title: "Star Wars Zero Company Review",
    publisher: "TechRadar",
    url: "https://www.techradar.com/gaming/star-wars-zero-company-review",
    kind: "press",
    checkedAt: "2026-08-30",
    note: "40-hour PC review, performance observations, and turn-based accessibility perspective.",
  },
  {
    id: "gamesradar-review",
    title: "Star Wars Zero Company Review",
    publisher: "GamesRadar+",
    url: "https://www.gamesradar.com/games/strategy/star-wars-zero-company-review/",
    kind: "press",
    checkedAt: "2026-08-30",
    note: "Launch review used only for the broad tactics/story consensus and stated reservations.",
  },
  {
    id: "windowscentral-review",
    title: "Star Wars Zero Company Review",
    publisher: "Windows Central",
    url: "https://www.windowscentral.com/gaming/star-wars-zero-company-review",
    kind: "press",
    checkedAt: "2026-08-30",
    note: "Launch review covering class depth, Bonds, equipment, campaign systems and console experience.",
  },
  {
    id: "gamesgg-settings",
    title: "Best PC Settings for Max FPS",
    publisher: "GAMES.GG",
    url: "https://games.gg/star-wars-zero-company/guides/star-wars-zero-company-best-pc-settings/",
    kind: "competitor",
    checkedAt: "2026-08-30",
    note: "Third-party settings test; results are not generalized beyond its stated hardware.",
  },
  {
    id: "reddit-geometry",
    title: "Environment Geometry Detail Performance Discussion",
    publisher: "r/ZeroCompany",
    url: "https://www.reddit.com/r/ZeroCompany/comments/1w01y1g/turn_off_the_environment_geometry_detail_setting/",
    kind: "community",
    checkedAt: "2026-08-30",
    note: "Conflicting player reports: large gain for some systems, little or no change for others.",
  },
  {
    id: "steamdeckhq",
    title: "Zero Company Is Not a Good Experience on Steam Deck",
    publisher: "Steam Deck HQ",
    url: "https://steamdeckhq.com/news/star-wars-zero-company-not-good-on-steam-deck/",
    kind: "press",
    checkedAt: "2026-08-30",
    note: "Launch test reporting sub-30 FPS native performance on the tested Deck.",
  },
  {
    id: "nexus-vortex",
    title: "Star Wars Zero Company Vortex Extension",
    publisher: "Nexus Mods",
    url: "https://www.nexusmods.com/site/mods/2174",
    kind: "community",
    checkedAt: "2026-08-30",
    note: "Official Nexus Vortex extension listing; does not make game mods officially supported by EA.",
  },
  {
    id: "zerocommand-modding",
    title: "Zero Company Modding Guide",
    publisher: "Zero Command Wiki",
    url: "https://wiki.zerocommand.gg/getting-started/modding",
    kind: "competitor",
    checkedAt: "2026-08-30",
    note: "Community installation ecosystem used for gap discovery, not copied as instructions.",
  },
  {
    id: "pcg-discord-mods",
    title: "No Official Mod Support Planned",
    publisher: "PC Gamer reporting Bit Reactor Discord Q&A",
    url: "https://www.pcgamer.com/games/rpg/star-wars-zero-company-wont-have-official-mod-support-confirms-bit-reactor-but-it-has-a-lot-of-respect-for-the-modding-community/",
    kind: "press",
    checkedAt: "2026-08-30",
    note: "Public reporting of a developer Discord answer; corroborated by EA FAQ.",
  },
  {
    id: "pcg-discord-jedi",
    title: "Tel-Rea Is the Only Jedi Padawan Operator",
    publisher: "PC Gamer reporting Bit Reactor Discord Q&A",
    url: "https://www.pcgamer.com/games/strategy/theres-only-one-jedi-operator-in-star-wars-zero-company-and-reckless-players-may-end-up-with-none-at-all-be-careful-that-nothing-unfortunate-happens-to-her/",
    kind: "press",
    checkedAt: "2026-08-30",
    note: "Public reporting of a developer Discord answer about Tel-Rea and permadeath.",
  },
  {
    id: "ea-tactics-basics",
    title: "Turn-Based Tactics and Combat Basics Guide",
    publisher: "EA Help",
    url: "https://help.ea.com/en/articles/star-wars/zero-company/turn-based-tactics-basics/",
    kind: "official",
    checkedAt: "2026-08-31",
    note: "Official three-AP turn, Cover, Overwatch, Backup, Advantage, Rally, Injury and Permadeath rules.",
  },
  {
    id: "starwars-how-to-play",
    title: "How to Play Star Wars Zero Company",
    publisher: "StarWars.com",
    url: "https://www.starwars.com/news/star-wars-zero-company-guide",
    kind: "official",
    checkedAt: "2026-08-31",
    note: "Official beginner guidance, Operations overview and the objective-first rule that not every mission requires defeating every enemy.",
  },
  {
    id: "steam-dev-faq",
    title: "Star Wars Zero Company FAQ",
    publisher: "Electronic Arts / Bit Reactor on Steam Community",
    url: "https://steamcommunity.com/app/2075800/discussions/0/586181093023024687/",
    kind: "official",
    checkedAt: "2026-08-31",
    note: "Developer-authored forum FAQ covering authored and Custom Operators, Den staff, Bonds, expiring content and mission types.",
  },
  {
    id: "gamesradar-weapons",
    title: "Best Weapons in Star Wars Zero Company",
    publisher: "GamesRadar+",
    url: "https://www.gamesradar.com/games/strategy/star-wars-zero-company-weapons/",
    kind: "press",
    checkedAt: "2026-08-31",
    note: "Launch-build explanation of weapon turn patterns, Armory swapping and special-Operator equipment exceptions.",
  },
  {
    id: "gamesradar-characters",
    title: "Best Star Wars Zero Company Characters and Team Comp",
    publisher: "GamesRadar+",
    url: "https://www.gamesradar.com/games/strategy/star-wars-zero-company-best-characters-team/",
    kind: "press",
    checkedAt: "2026-08-31",
    note: "Launch character-role and equipment observations used only as a tactical handoff, not an official roster ranking.",
  },
  {
    id: "steam-expert-tips",
    title: "Expert Tips?",
    publisher: "Steam Community players",
    url: "https://steamcommunity.com/app/2075800/discussions/0/590687864233346675/",
    kind: "community",
    checkedAt: "2026-08-31",
    note: "Player discussion showing that weapon value changes with movement, difficulty, mods and squad role; not treated as consensus.",
  },
  {
    id: "reddit-beginner-friendly",
    title: "Will This Game Be Beginner Friendly?",
    publisher: "r/ZeroCompany",
    url: "https://www.reddit.com/r/ZeroCompany/comments/1vycfob/will_this_game_be_beginner_friendly/",
    kind: "community",
    checkedAt: "2026-08-31",
    note: "Pre-launch and launch-window player perspectives on difficulty, pacing and learning the tactics format; anecdotal only.",
  },
  {
    id: "epic-operators",
    title: "Best Builds for Each Operator",
    publisher: "Epic Games Store",
    url: "https://store.epicgames.com/news/star-wars-zero-company-guide-best-builds-for-each-operator",
    kind: "press",
    checkedAt: "2026-09-01",
    note: "Launch-build companion recruitment, unique Talent and starting-Specialization observations; used as a labeled gameplay cross-check, not as official canon.",
  },
  {
    id: "reddit-bond-strategies",
    title: "Bond Strategies",
    publisher: "r/ZeroCompany",
    url: "https://www.reddit.com/r/ZeroCompany/comments/1w2lngy/bond_strategies/",
    kind: "community",
    checkedAt: "2026-09-01",
    note: "Small, self-selected launch discussion about rotating Operators and building Bonds; exact XP values and optimal routes are not treated as settled facts.",
  },
  {
    id: "reddit-roster-rotation",
    title: "What Is the Point of a Big Roster?",
    publisher: "r/ZeroCompany",
    url: "https://www.reddit.com/r/ZeroCompany/comments/1w0urml/whats_the_point_of_having_a_big_roster_if_you_can/",
    kind: "community",
    checkedAt: "2026-09-01",
    note: "Player debate over a fixed four-Operator squad versus rotation for mission roles, Injuries and Bonds; anecdotal and patch-sensitive.",
  },
  {
    id: "reddit-weapons-specializations",
    title: "Best Weapons for Each Specialization?",
    publisher: "r/ZeroCompany",
    url: "https://www.reddit.com/r/ZeroCompany/comments/1w1owpo/best_weapons_for_each_specialization/",
    kind: "community",
    checkedAt: "2026-09-01",
    note: "Launch discussion comparing Pistol, Rifle, Repeater and Longarm across Specializations; opinions conflict and are not treated as a settled tier list.",
  },
  {
    id: "reddit-repeater-debate",
    title: "Suggested Change to Repeaters",
    publisher: "r/ZeroCompany",
    url: "https://www.reddit.com/r/ZeroCompany/comments/1w2cnte/suggested_change_to_repeaters/",
    kind: "community",
    checkedAt: "2026-09-01",
    note: "Player examples both favoring and rejecting Repeater loadouts; useful for exposing map, AP and build dependencies rather than naming one winner.",
  },
  {
    id: "reddit-difficulty-psa",
    title: "Difficulty PSA for Genre Players",
    publisher: "r/ZeroCompany",
    url: "https://www.reddit.com/r/ZeroCompany/comments/1w08a8h/difficulty_psa_if_you_have_played_the_genre_play/",
    kind: "community",
    checkedAt: "2026-09-01",
    note: "Launch discussion comparing Hard and Expert for experienced tactics players; self-selected experiences, not an official difficulty prescription.",
  },
  {
    id: "reddit-difficulty-question",
    title: "How Is the Difficulty?",
    publisher: "r/ZeroCompany",
    url: "https://www.reddit.com/r/ZeroCompany/comments/1w0gl3x/how_is_the_difficulty/",
    kind: "community",
    checkedAt: "2026-09-01",
    note: "Players compare Normal with prior XCOM experience and disagree about when difficulty rises; used to frame player profiles, not hidden modifiers.",
  },
  {
    id: "reddit-permadeath-threat",
    title: "Permadeath Feels Nonexistent",
    publisher: "r/ZeroCompany",
    url: "https://www.reddit.com/r/ZeroCompany/comments/1w2v9g1/permadeath_feels_non_existent/",
    kind: "community",
    checkedAt: "2026-09-01",
    note: "Expert/Beskar player reports about perceived Permadeath pressure; anecdotal evidence of repeated demand, not a universal difficulty finding.",
  },
];

export const sourceById = new Map(sources.map((source) => [source.id, source]));

export function resolveSources(ids: string[]): Source[] {
  return ids.map((id) => {
    const source = sourceById.get(id);
    if (!source) throw new Error(`Unknown source id: ${id}`);
    return source;
  });
}
