import type { Source } from "./types";

export const sources: Source[] = [
  { id: "allthings-den-priorities", title: "Best Base Upgrades and Influence Zones", publisher: "All Things How", url: "https://allthings.how/star-wars-zero-company-best-base-upgrades-and-influence-zones/", kind: "competitor", checkedAt: "2026-09-23", note: "Named Networking, equipment-slot, shop-quality and weapon branches. Used with contrasting player advice for conditional priorities; exact costs and unlock levels remain excluded." },
  { id: "ops-enemy-intelligence", title: "Enemy Intelligence Walkthrough", publisher: "Zero Company Ops", url: "https://zerocompanyops.com/missions/enemy-intelligence", kind: "competitor", checkedAt: "2026-09-23", note: "Community objective list: control platform, data downlink, Visser, Escape. Supports a mission-specific sequence, not exact spawns, route geometry or first-hand playtesting." },
  { id: "reddit-citadel-boss", title: "I just hit one of the boss fights and need to rant", publisher: "Reddit r/ZeroCompany players", url: "https://www.reddit.com/r/ZeroCompany/comments/1w1yla9/i_just_hit_one_of_the_boss_fights_and_need_to_rant/", kind: "community", checkedAt: "2026-09-23", note: "Discussion identifies the mining-citadel encounter; separate players describe Jedi displacement and Assault/Heavy control for Miasma. Current patch, ability details and completion condition remain unverified." },
  { id: "ea-community-qa", title: "Answering the Internet's Biggest Questions about SWZC", publisher: "Electronic Arts / Bit Reactor", url: "https://www.ea.com/games/starwars/zero-company/news/answering-biggest-questions", kind: "official", checkedAt: "2026-09-23", note: "July 21 developer Q&A: mission categories, deadline rules, squad restrictions and objective-dependent Overwatch advice. Pre-launch scope; not a post-patch boss test." },
  { id: "reddit-companion-deadlines", title: "Can I avoid missing companion missions without metagame knowledge?", publisher: "Reddit r/ZeroCompany players", url: "https://www.reddit.com/r/ZeroCompany/comments/1wg3qzt/can_i_avoid_missing_companion_missions_without/", kind: "community", checkedAt: "2026-09-23", note: "Luco/Tel/intervention deadline collisions and underestimated prerequisite Intel. Reports support planning examples, not a fixed universal calendar." },
  { id: "reddit-reinforcement-pressure", title: "Reinforcements", publisher: "Reddit r/ZeroCompany players", url: "https://www.reddit.com/r/ZeroCompany/comments/1w69dfg/reinforcements/", kind: "community", checkedAt: "2026-09-23", note: "Players describe reinforcement pressure and objective-first movement. No universal spawn count or first-turn immunity adopted." },
  { id: "steam-infinite-reinforcements", title: "Infinite reinforcements...", publisher: "Steam Community players", url: "https://steamcommunity.com/app/2075800/discussions/0/590688141302680432/", kind: "community", checkedAt: "2026-09-23", note: "Movement to objectives and extraction amid repeated arrivals. Used as player-intent evidence, not a verified mission script." },
  { id: "reddit-credit-budget", title: "About the credits situation...", publisher: "Reddit r/ZeroCompany players", url: "https://www.reddit.com/r/ZeroCompany/comments/1wjtxn1/about_the_credits_situation/", kind: "community", checkedAt: "2026-09-23", note: "Conflicting Black Market, medical, income-Operator and equipment-sale strategies. Recommendations remain conditional; no fixed income or stacking formula adopted." },
  { id: "reddit-credit-shortage", title: "Credits", publisher: "Reddit r/ZeroCompany players", url: "https://www.reddit.com/r/ZeroCompany/comments/1w6bh6l/credits/", kind: "community", checkedAt: "2026-09-23", note: "Budget and late material-shortage experiences; no infinite farming claim." },
  { id: "prodigy-den-upgrades", title: "Den Upgrade Priority Guide", publisher: "Prodigygamers", url: "https://prodigygamers.com/2026/09/01/star-wars-zero-company-den-upgrade-priority-guide-build-order-tier-list/", kind: "competitor", checkedAt: "2026-09-23", note: "September 1 opinion favors shop quality and selected Crew improvements. Exact costs, unlock levels, passive Bond values and mandatory build order not adopted without stronger evidence." },
  { id: "reddit-umbara-softlock", title: "Spoiler: Gamebreaking Bug", publisher: "Reddit r/ZeroCompany players", url: "https://www.reddit.com/r/ZeroCompany/comments/1w3d4bs/spoiler_gamebreaking_bug/", kind: "community", checkedAt: "2026-09-23", note: "PS5/PS5 Pro Umbara lift and Holotable cutscene reports. Installed builds and causes are not established. Search and page snapshots expose different reply coverage; combined reinstall/settings anecdotes are not treated as confirmed fixes." },
  { id: "reddit-no-ap", title: "No AP bug?", publisher: "Reddit r/ZeroCompany players", url: "https://www.reddit.com/r/ZeroCompany/comments/1wk2lnj/no_ap_bug/", kind: "community", checkedAt: "2026-09-23", note: "Beskar retrieval report with a Custom Operator unable to act and skipped enemy turns. Platform, build and cause remain unconfirmed." },
  { id: "starwars-visser", title: "Visser", publisher: "StarWars.com Databank", url: "https://www.starwars.com/databank/visser", kind: "official", checkedAt: "2026-09-23", note: "Official character identity and spelling. Does not establish encounter numbers or a boss solution." },
  { id: "allthings-visser", title: "How to Beat Visser in Retake Mordant Citadel", publisher: "All Things How", url: "https://allthings.how/star-wars-zero-company-how-to-beat-visser-in-retake-mordant-citadel/", kind: "competitor", checkedAt: "2026-09-23", note: "September 2 encounter coverage with linked video timestamps: escort, Miasma, displacement and remaining-enemy objective. No first-hand replay by this site; no exact HP or guaranteed kill adopted." },
  { id: "indiatimes-visser", title: "Retake Mordant Citadel Boss Guide", publisher: "IndiaTimes SportsRant", url: "https://sportsrant.indiatimes.com/gaming/star-wars-zero-company-retake-mordant-citadel-boss-guide/amp_articleshow/133761428.html", kind: "press", checkedAt: "2026-09-23", note: "September 4 guide overlaps heavily with All Things How. Corroborates naming and described route but is not counted as an independent playtest." },
  { id: "reddit-visser-difficulty", title: "This game went from easy to unbelievably hard within one mission", publisher: "Reddit r/ZeroCompany players", url: "https://www.reddit.com/r/ZeroCompany/comments/1wgpq86/this_game_went_from_easy_to_unbelievably_hard/", kind: "community", checkedAt: "2026-09-23", note: "Difficulty spike and support/retaliation complaints. Inconsistent spelling and no precise mission/build proof: used for demand and diagnostic questions, not Citadel stats or universal mechanics." },
  {
    id: "ea-common-issues",
    title: "Troubleshoot common STAR WARS Zero Company issues",
    publisher: "EA Help",
    url: "https://help.ea.com/en/articles/star-wars/zero-company/troubleshoot-common-issues/",
    kind: "official",
    checkedAt: "2026-09-23",
    note: "Restart, game/system updates and PC repair guidance; saving precaution before quitting. General troubleshooting is not a guaranteed repair for an already damaged save.",
  },
  {
    id: "ea-news-index",
    title: "STAR WARS Zero Company News and Updates",
    publisher: "Electronic Arts",
    url: "https://www.ea.com/games/starwars/zero-company/news",
    kind: "official",
    checkedAt: "2026-09-23",
    note: "Patch 1.1 was the newest patch article found in the official news listing during this check; platform installation and individual results require separate verification.",
  },
  {
    id: "ea-game",
    title: "Star Wars Zero Company",
    publisher: "Electronic Arts",
    url: "https://www.ea.com/games/starwars/zero-company",
    kind: "official",
    checkedAt: "2026-08-30",
    note: "Official overview, supported platforms, story premise, Operators, Bonds, and customization.",
  },
  {
    id: "ea-faq",
    title: "Star Wars Zero Company FAQ",
    publisher: "Electronic Arts",
    url: "https://www.ea.com/games/starwars/zero-company/faq",
    kind: "official",
    checkedAt: "2026-09-23",
    note: "Official requirements, CPU-bound and upscaling guidance, plus Operations versus Tactical Missions, expiry and Cycle rules rechecked September 23. Also covers launch features and permadeath.",
  },
  {
    id: "ea-patch-1-1",
    title: "Star Wars Zero Company 1.1 Patch Notes",
    publisher: "Electronic Arts",
    url: "https://www.ea.com/games/starwars/zero-company/news/patch-notes-1-1",
    kind: "official",
    checkedAt: "2026-09-23",
    note: "September 9 release: crash, visual-stutter and save fixes; Secondary Specializations count in Operation checks; Geometry Detail Off advice is scoped to minimum-spec GTX 10-series and RTX 20-series cards. Does not prove changes to named Operation reward tables or universal performance gains.",
  },
  {
    id: "starwars-play-guide",
    title: "How to Play Star Wars Zero Company - Available Now",
    publisher: "StarWars.com",
    url: "https://www.starwars.com/news/star-wars-zero-company-guide",
    kind: "official",
    checkedAt: "2026-09-23",
    note: "August 27 official introduction to Operations, Intel, Bonds, injuries and Cycle planning. Supports general mechanics, not the four named Operations' numeric rewards.",
  },
  {
    id: "ea-specializations",
    title: "Specializations",
    publisher: "Electronic Arts",
    url: "https://www.ea.com/games/starwars/zero-company/specializations-hub",
    kind: "official",
    checkedAt: "2026-08-30",
    note: "Official list of eight standard Specializations and the ability model.",
  },
  {
    id: "ea-class-guide",
    title: "Specialization and Weapon Class Guide",
    publisher: "EA Help",
    url: "https://help.ea.com/id/articles/star-wars/zero-company/specialization-and-weapon-class-guide/",
    kind: "official",
    checkedAt: "2026-08-30",
    note: "Official role, ability, weapon, and playstyle guidance for each standard Specialization.",
  },
  {
    id: "ea-gameplay-overview",
    title: "Lead Zero Company to Victory",
    publisher: "Electronic Arts",
    url: "https://www.ea.com/games/starwars/zero-company/news/lead-zero-company-to-victory",
    kind: "official",
    checkedAt: "2026-08-30",
    note: "Official combat, AP, Advantage, injuries, Operators, Den, Operations, and mission overview.",
  },
  {
    id: "ea-official-video",
    title: "Star Wars Zero Company Official Gameplay Trailer",
    publisher: "EA Star Wars on YouTube",
    url: "https://www.youtube.com/watch?v=WxLUZ1omFA8",
    kind: "video",
    checkedAt: "2026-08-30",
    note: "Official video description and gameplay feature overview; no third-party claims used.",
  },
  {
    id: "steam-store",
    title: "STAR WARS Zero Company on Steam",
    publisher: "Valve / Electronic Arts",
    url: "https://store.steampowered.com/app/2075800/STAR_WARS_Zero_Company/",
    kind: "official",
    checkedAt: "2026-08-30",
    note: "Release, price, editions, languages, system requirements, features, and 53 achievements.",
  },
  {
    id: "steam-store-hungarian",
    title: "STAR WARS Zero Company on Steam - Hungarian storefront",
    publisher: "Valve / Electronic Arts",
    url: "https://store.steampowered.com/app/2075800/STAR_WARS_Zero_Company/?l=hungarian",
    kind: "official",
    checkedAt: "2026-09-03",
    note: "Hungarian storefront language matrix showing Magyar as not supported for interface, subtitles and full audio.",
  },
  {
    id: "google-trends-help",
    title: "Find related searches",
    publisher: "Google Trends Help",
    url: "https://support.google.com/trends/answer/4355000?hl=en",
    kind: "official",
    checkedAt: "2026-09-03",
    note: "Official explanation that Rising search percentages compare growth with the previous period and Breakout means growth above 5000%.",
  },
  {
    id: "steamdb-config",
    title: "STAR WARS Zero Company Configuration",
    publisher: "SteamDB",
    url: "https://steamdb.info/app/2075800/config/",
    kind: "community",
    checkedAt: "2026-09-02",
    note: "Timestamped Steam metadata cross-check for App ID, supported-language matrix and Valve's Unsupported Steam Deck test record; SteamDB is not Valve.",
  },
  {
    id: "starwars-cast",
    title: "SDCC 2026: Zero Company Cast Announcement",
    publisher: "StarWars.com",
    url: "https://www.starwars.com/news/sdcc-star-wars-zero-company-cast-announce",
    kind: "official",
    checkedAt: "2026-08-30",
    note: "Official voice cast and character background statements.",
  },
  {
    id: "ea-forums",
    title: "STAR WARS Zero Company Forum",
    publisher: "EA Forums",
    url: "https://forums.ea.com/category/star-wars-games-en/discussions/star-wars-zero-company-en",
    kind: "official",
    checkedAt: "2026-08-30",
    note: "Official community-manager issue posts and player reports; individual reports are not universal facts.",
  },
  {
    id: "steam-issue-update",
    title: "STAR WARS Zero Company Issue Updates",
    publisher: "EA Star Wars on Steam",
    url: "https://steamcommunity.com/app/2075800/discussions/0/590687864233291254/",
    kind: "official",
    checkedAt: "2026-09-03",
    note: "Historical September 3 snapshot of developer-pinned crash, driver, CPU-threading and Intel stability guidance. Use the separately listed September 9 patch 1.1 notes for the later released fixes; this record is not a current claim that no patch exists.",
  },
  {
    id: "pcg-best-class",
    title: "Best Starting Class in Star Wars Zero Company",
    publisher: "PC Gamer",
    url: "https://www.pcgamer.com/games/strategy/star-wars-zero-company-best-class-specialization/",
    kind: "press",
    checkedAt: "2026-08-30",
    note: "Launch-version Scoundrel recommendation and early-game alternatives.",
  },
  {
    id: "pcg-respec",
    title: "How to Respec in Star Wars Zero Company",
    publisher: "PC Gamer",
    url: "https://www.pcgamer.com/games/strategy/star-wars-zero-company-respec-change-class/",
    kind: "press",
    checkedAt: "2026-08-30",
    note: "Cycle 3 unlock, Focus Point refunds, and named-Talent limits.",
  },
  {
    id: "mobalytics-tier",
    title: "All Specializations Ranked",
    publisher: "Mobalytics",
    url: "https://mobalytics.gg/gamebase/guides/star-wars-zero-company-specialization-tier-list",
    kind: "competitor",
    checkedAt: "2026-09-02",
    note: "Post-launch ranking that places Heavy and Scout in S tier and Scoundrel in C; used to show methodology disagreement, not as consensus.",
  },
  {
    id: "destructoid-tier",
    title: "Best Star Wars Zero Company Class and Specialization Tier List",
    publisher: "Destructoid",
    url: "https://www.destructoid.com/best-star-wars-zero-company-class-and-specialization-tier-list/",
    kind: "press",
    checkedAt: "2026-09-02",
    note: "Post-launch ranking that places Scout, Sharpshooter and Assault in S tier while putting Scoundrel and Heavy in B; used as a contrasting methodology.",
  },
  {
    id: "reddit-expert-builds",
    title: "Expert Completion with Minimal Reloads",
    publisher: "r/ZeroCompany",
    url: "https://www.reddit.com/r/ZeroCompany/comments/1w3k0y3/completed_the_game_on_expert_no_beskar_minimal/",
    kind: "community",
    checkedAt: "2026-09-02",
    note: "One player's completed Expert-run notes on Heavy early value and a Medic/Scoundrel Hawks route; useful experience evidence, not a universal ranking.",
  },
  {
    id: "reddit-hawks-launch",
    title: "Class for Hawks?",
    publisher: "r/ZeroCompany",
    url: "https://www.reddit.com/r/ZeroCompany/comments/1w0o139/class_for_hawks/",
    kind: "community",
    checkedAt: "2026-09-02",
    note: "Post-launch player discussion comparing Hawks pairings and the trade-off between damage, setup and support; individual builds are not controlled benchmarks.",
  },
  {
    id: "allthings-hawks-build",
    title: "Best Hawks Build — Gunslinger and Medic",
    publisher: "All Things How",
    url: "https://allthings.how/star-wars-zero-company-best-hawks-build-gunslinger-medic/",
    kind: "competitor",
    checkedAt: "2026-09-02",
    note: "Post-launch Gunslinger/Medic route used as one complete pairing example; exact talent orders remain excluded without matching first-hand patch testing.",
  },
  {
    id: "reddit-hawks",
    title: "Best Class for Hawks Discussion",
    publisher: "r/ZeroCompany",
    url: "https://www.reddit.com/r/ZeroCompany/comments/1vxzp45/best_class_for_hawks/",
    kind: "community",
    checkedAt: "2026-08-30",
    note: "Community disagreement across Scoundrel, Medic, Gunslinger, and Scout routes.",
  },
  {
    id: "reddit-squads",
    title: "What Is Your Squad Composition?",
    publisher: "r/ZeroCompany",
    url: "https://www.reddit.com/r/ZeroCompany/comments/1w2do3c/whats_your_squad_comp/",
    kind: "community",
    checkedAt: "2026-08-30",
    note: "Early player squad patterns; small and self-selected sample.",
  },
  {
    id: "destructoid-squads",
    title: "Best Squads to Use in Star Wars Zero Company",
    publisher: "Destructoid",
    url: "https://www.destructoid.com/best-squads-to-use-in-star-wars-zero-company/",
    kind: "press",
    checkedAt: "2026-08-30",
    note: "Named-Operator squad suggestions used as one external viewpoint.",
  },
  {
    id: "allthings-chapters",
    title: "All 14 Chapters and Main Story Missions",
    publisher: "All Things How",
    url: "https://allthings.how/star-wars-zero-company-all-14-chapters-and-main-story-missions/",
    kind: "competitor",
    checkedAt: "2026-08-30",
    note: "Community chapter order cross-check; chapter guides remain gated until independently verified.",
  },
  {
    id: "whisper-hutt-debt",
    title: "In Debt to the Hutts: 80,000 Credits Guide",
    publisher: "Whisper of the House",
    url: "https://www.whisperofthehouse.com/star-wars-zero-company/in-debt-to-the-hutts-walkthrough",
    kind: "competitor",
    checkedAt: "2026-09-01",
    note: "A launch-route account covering the 80,000-Credit counter, Gorga chain, Republic Intelligence contract and Payback; retained as a route lead pending local replay.",
  },
  {
    id: "reddit-credit-economy",
    title: "Is the Credit Economy Broken?",
    publisher: "r/ZeroCompany",
    url: "https://www.reddit.com/r/ZeroCompany/comments/1w3v7as/is_it_just_me_or_is_the_credit_economy_of_this/",
    kind: "community",
    checkedAt: "2026-09-01",
    note: "Current player discussion about scarce Credits and Den or Black Market trade-offs; not direct proof of the story-debt route.",
  },
  {
    id: "gamersheroes-choices",
    title: "Star Wars Zero Company Choices Guide",
    publisher: "Gamers Heroes",
    url: "https://www.gamersheroes.com/game-guides/star-wars-zero-company-choices-guide/",
    kind: "competitor",
    checkedAt: "2026-09-23",
    note: "Rechecked Back Channels packages and Strange Bedfellows, Protection Application (+4 Zone Cresh versus Databank +3), and Sloppy's reported 50-Intel Analyze / 1,500-Credit Pay Off charges. Charge stacking and same-version results remain unresolved; other Operations retain their earlier checks.",
  },
  {
    id: "showgamer-choices",
    title: "Star Wars Zero Company Walkthrough — All Choices and Outcomes",
    publisher: "ShowGamer",
    url: "https://showgamer.com/en/guides/5371-prohozhdenie-star-wars-zero-company",
    kind: "competitor",
    checkedAt: "2026-09-23",
    note: "Back Channels packages and Strange Bedfellows rechecked against Gamers Heroes. Matching text is corroboration, not proof of independent testing; Ship Adrift and Help Wanted retain the earlier review scope.",
  },
  {
    id: "allthings-storm-basin",
    title: "How to Rescue the Storm Basin Civilians",
    publisher: "All Things How",
    url: "https://allthings.how/star-wars-zero-company-how-to-rescue-the-storm-basin-civilians/",
    kind: "competitor",
    checkedAt: "2026-09-02",
    note: "First-person route account confirming that Runa unlocks Storm Basin while Neesh unlocks the Station Mission.",
  },
  {
    id: "zerocompany-tools-sloppy-supply-route",
    title: "Sloppy Supply Route",
    publisher: "Zero Company Databank",
    url: "https://www.zerocompany.tools/operations/sloppy-supply-route",
    kind: "competitor",
    checkedAt: "2026-09-23",
    note: "Current page labels build 25134257: 100-Intel entry, three-turn availability, three options and no-droids restriction on Direct Raid. Repeated reward groups do not establish one flat probability pool; +3 Influence conflicts with the player's +4 Direct Raid report. First-hand capture pending.",
  },
  {
    id: "zerocompany-tools-help-wanted",
    title: "Help Wanted",
    publisher: "Zero Company Databank",
    url: "https://www.zerocompany.tools/operations/help-wanted",
    kind: "competitor",
    checkedAt: "2026-09-23",
    note: "Build 25134257 page reviewed for six scene prompts, roster requirements, risks and outcomes. Shared 40-Intel / two-turn fields are not separately verified for each variant; extracted weights are not measured probabilities and Odra's narrative link does not prove a guaranteed trigger.",
  },
  {
    id: "zerocompany-tools-protection-application",
    title: "Protection Application",
    publisher: "Zero Company Databank",
    url: "https://www.zerocompany.tools/operations/protection-application",
    kind: "competitor",
    checkedAt: "2026-09-23",
    note: "Build 25134257 record: 50 Intel, three-turn availability, 1,000 Credits / -25 team Bond XP versus +10 roster Bond XP. Its +3 Influence differs from Gamers Heroes' +4 Zone Cresh; no reason for the discrepancy or later Imperial retaliation is established.",
  },
  {
    id: "zerocompany-tools-about",
    title: "About the Zero Company Databank",
    publisher: "Zero Company Databank",
    url: "https://www.zerocompany.tools/about",
    kind: "competitor",
    checkedAt: "2026-09-03",
    note: "Extracted game text for Inspect Mode and hover help; useful for UI explanation, not hidden combat data.",
  },
  {
    id: "zerocompany-tools-nebulous-pursuit",
    title: "Nebulous Pursuit",
    publisher: "Zero Company Databank",
    url: "https://www.zerocompany.tools/operations/nebulous-pursuit",
    kind: "competitor",
    checkedAt: "2026-09-02",
    note: "Extracted build 24874058 Operation record for the first pursuit's cost, expiry, Operator requirement, destinations and displayed reward fields.",
  },
  {
    id: "powerup-nebulous-pursuit",
    title: "Star Wars Zero Company: Nebulous Pursuit Guide",
    publisher: "Power Up Gaming",
    url: "https://powerupgaming.co.uk/2026/08/31/star-wars-zero-company-nebulous-pursuit-guide/",
    kind: "competitor",
    checkedAt: "2026-09-02",
    note: "Post-launch guide covering both pursuit stages, reported randomized destinations, rewards and the Lotho Minor injury-risk trade-off.",
  },
  {
    id: "gamerblurb-nebulous-pursuit",
    title: "Star Wars Zero Company Nebulous Pursuit Best Choice",
    publisher: "GamerBlurb",
    url: "https://gamerblurb.com/star-wars-zero-company/star-wars-zero-company-nebulous-pursuit-best-choice",
    kind: "competitor",
    checkedAt: "2026-09-02",
    note: "Independent launch-window reports that the successful destination varies by attempt; used to reject a universal fixed answer.",
  },
  {
    id: "allthings-achievements",
    title: "How to Unlock All 53 Achievements",
    publisher: "All Things How",
    url: "https://allthings.how/star-wars-zero-company-how-to-unlock-all-53-achievements/",
    kind: "competitor",
    checkedAt: "2026-08-30",
    note: "Category and unlock-condition cross-check; uncertain missability is labeled.",
  },
  {
    id: "truetrophies-list",
    title: "STAR WARS Zero Company Trophies",
    publisher: "TrueTrophies",
    url: "https://www.truetrophies.com/game/Star-Wars-Zero-Company/trophies",
    kind: "community",
    checkedAt: "2026-09-02",
    note: "PS5 list confirming 53 trophies, the 44/6/2/1 distribution and the published difficulty requirements.",
  },
  {
    id: "wehunt-platinum",
    title: "STAR WARS Zero Company — Zero Company Legend Platinum Guide",
    publisher: "WeHunt",
    url: "https://wehunt.gg/guides/star-wars-zero-companytm-cookiemonster33-npwr41236_00-9015d73d",
    kind: "community",
    checkedAt: "2026-09-02",
    note: "Two-campaign launch roadmap and first-completion reports for difficulty stacking and long counters; route estimates remain community evidence.",
  },
  {
    id: "reddit-platinum-guide",
    title: "Zero Company Platinum Guide Updates",
    publisher: "r/Trophies",
    url: "https://www.reddit.com/r/Trophies/comments/1w1t91p/star_wars_zero_company_my_best_attempt_at_a_guide/",
    kind: "community",
    checkedAt: "2026-09-02",
    note: "Dated community corrections after early completions, including reported difficulty stacking and cross-campaign counters; not treated as official mechanics documentation.",
  },
  {
    id: "pcg-review",
    title: "Star Wars Zero Company Review",
    publisher: "PC Gamer",
    url: "https://www.pcgamer.com/games/strategy/star-wars-zero-company-review/",
    kind: "press",
    checkedAt: "2026-08-30",
    note: "Full-campaign review, PC technical observations, and Steam Deck test context.",
  },
  {
    id: "pcg-linear-abilities",
    title: "Swap the Radial Ability Menu for Linear Ability Selection",
    publisher: "PC Gamer",
    url: "https://www.pcgamer.com/games/strategy/psa-swap-the-radial-ability-menu-in-star-wars-zero-company-for-more-of-a-trad-xcom-style-experience/",
    kind: "press",
    checkedAt: "2026-08-31",
    note: "Documents the Radial, Linear and Hybrid Ability Selection Style options as an input preference; provides no FPS benchmark or universal-best claim.",
  },
  {
    id: "techradar-review",
    title: "Star Wars Zero Company Review",
    publisher: "TechRadar",
    url: "https://www.techradar.com/gaming/star-wars-zero-company-review",
    kind: "press",
    checkedAt: "2026-08-30",
    note: "40-hour PC review, performance observations, and turn-based accessibility perspective.",
  },
  {
    id: "gamesradar-review",
    title: "Star Wars Zero Company Review",
    publisher: "GamesRadar+",
    url: "https://www.gamesradar.com/games/strategy/star-wars-zero-company-review/",
    kind: "press",
    checkedAt: "2026-08-30",
    note: "Launch review used only for the broad tactics/story consensus and stated reservations.",
  },
  {
    id: "windowscentral-review",
    title: "Star Wars Zero Company Review",
    publisher: "Windows Central",
    url: "https://www.windowscentral.com/gaming/star-wars-zero-company-review",
    kind: "press",
    checkedAt: "2026-08-30",
    note: "Launch review covering class depth, Bonds, equipment, campaign systems and console experience.",
  },
  {
    id: "gamesgg-settings",
    title: "Best PC Settings for Max FPS",
    publisher: "GAMES.GG",
    url: "https://games.gg/star-wars-zero-company/guides/star-wars-zero-company-best-pc-settings/",
    kind: "competitor",
    checkedAt: "2026-08-30",
    note: "Third-party settings test; results are not generalized beyond its stated hardware.",
  },
  {
    id: "reddit-geometry",
    title: "Environment Geometry Detail Performance Discussion",
    publisher: "r/ZeroCompany",
    url: "https://www.reddit.com/r/ZeroCompany/comments/1w01y1g/turn_off_the_environment_geometry_detail_setting/",
    kind: "community",
    checkedAt: "2026-08-30",
    note: "Conflicting player reports: large gain for some systems, little or no change for others.",
  },
  {
    id: "reddit-performance-megathread",
    title: "Bug, Glitches and Technical Issues Megathread",
    publisher: "r/ZeroCompany",
    url: "https://www.reddit.com/r/ZeroCompany/comments/1vzz3b1/megathread_bug_glitches_and_technical_issues/",
    kind: "community",
    checkedAt: "2026-09-02",
    note: "Post-launch hardware and symptom reports used to separate low FPS, startup crashes and scene-specific issues; not a controlled benchmark.",
  },
  {
    id: "reddit-pc-stutter-reports",
    title: "Zero Company PC Performance Reports",
    publisher: "r/ZeroCompany",
    url: "https://www.reddit.com/r/ZeroCompany/comments/1w01fbc/what_happened_here_havnt_heard_anything_really/",
    kind: "community",
    checkedAt: "2026-09-02",
    note: "Conflicting reports of high-FPS stutter, shader-compilation stutter, Den drops and stable systems; used to define symptoms rather than promise a fix.",
  },
  {
    id: "steamdeckhq",
    title: "Zero Company Is Not a Good Experience on Steam Deck",
    publisher: "Steam Deck HQ",
    url: "https://steamdeckhq.com/news/star-wars-zero-company-not-good-on-steam-deck/",
    kind: "press",
    checkedAt: "2026-08-30",
    note: "Launch test reporting sub-30 FPS native performance on the tested Deck.",
  },
  {
    id: "nexus-vortex",
    title: "Star Wars Zero Company Vortex Extension",
    publisher: "Nexus Mods",
    url: "https://www.nexusmods.com/site/mods/2174",
    kind: "community",
    checkedAt: "2026-08-30",
    note: "Official Nexus Vortex extension listing; does not make game mods officially supported by EA.",
  },
  {
    id: "nexus-full-info-inspect-mode",
    title: "Full Info In Inspect Mode",
    publisher: "Nexus Mods",
    url: "https://www.nexusmods.com/starwarszerocompany/mods/50",
    kind: "community",
    checkedAt: "2026-09-03",
    note: "UI mod that adds extra unit stats to Inspect Mode; separated from the built-in game feature and treated as patch-sensitive.",
  },
  {
    id: "zerocommand-modding",
    title: "Zero Company Modding Guide",
    publisher: "Zero Command Wiki",
    url: "https://wiki.zerocommand.gg/getting-started/modding",
    kind: "competitor",
    checkedAt: "2026-08-30",
    note: "Community installation ecosystem used for gap discovery, not copied as instructions.",
  },
  {
    id: "pcg-discord-mods",
    title: "No Official Mod Support Planned",
    publisher: "PC Gamer reporting Bit Reactor Discord Q&A",
    url: "https://www.pcgamer.com/games/rpg/star-wars-zero-company-wont-have-official-mod-support-confirms-bit-reactor-but-it-has-a-lot-of-respect-for-the-modding-community/",
    kind: "press",
    checkedAt: "2026-08-30",
    note: "Public reporting of a developer Discord answer; corroborated by EA FAQ.",
  },
  {
    id: "pcg-discord-jedi",
    title: "Tel-Rea Is the Only Jedi Padawan Operator",
    publisher: "PC Gamer reporting Bit Reactor Discord Q&A",
    url: "https://www.pcgamer.com/games/strategy/theres-only-one-jedi-operator-in-star-wars-zero-company-and-reckless-players-may-end-up-with-none-at-all-be-careful-that-nothing-unfortunate-happens-to-her/",
    kind: "press",
    checkedAt: "2026-08-30",
    note: "Public reporting of a developer Discord answer about Tel-Rea and permadeath.",
  },
  {
    id: "ea-tactics-basics",
    title: "Turn-Based Tactics and Combat Basics Guide",
    publisher: "EA Help",
    url: "https://help.ea.com/en/articles/star-wars/zero-company/turn-based-tactics-basics/",
    kind: "official",
    checkedAt: "2026-08-31",
    note: "Official three-AP turn, Cover, Overwatch, Backup, Advantage, Rally, Injury and Permadeath rules.",
  },
  {
    id: "starwars-how-to-play",
    title: "How to Play Star Wars Zero Company",
    publisher: "StarWars.com",
    url: "https://www.starwars.com/news/star-wars-zero-company-guide",
    kind: "official",
    checkedAt: "2026-08-31",
    note: "Official beginner guidance, Operations overview and the objective-first rule that not every mission requires defeating every enemy.",
  },
  {
    id: "steam-dev-faq",
    title: "Star Wars Zero Company FAQ",
    publisher: "Electronic Arts / Bit Reactor on Steam Community",
    url: "https://steamcommunity.com/app/2075800/discussions/0/586181093023024687/",
    kind: "official",
    checkedAt: "2026-08-31",
    note: "Developer-authored forum FAQ covering authored and Custom Operators, Den staff, Bonds, expiring content and mission types.",
  },
  {
    id: "gamesradar-weapons",
    title: "Best Weapons in Star Wars Zero Company",
    publisher: "GamesRadar+",
    url: "https://www.gamesradar.com/games/strategy/star-wars-zero-company-weapons/",
    kind: "press",
    checkedAt: "2026-08-31",
    note: "Launch-build explanation of weapon turn patterns, Armory swapping and special-Operator equipment exceptions.",
  },
  {
    id: "gamesradar-characters",
    title: "Best Star Wars Zero Company Characters and Team Comp",
    publisher: "GamesRadar+",
    url: "https://www.gamesradar.com/games/strategy/star-wars-zero-company-best-characters-team/",
    kind: "press",
    checkedAt: "2026-08-31",
    note: "Launch character-role and equipment observations used only as a tactical handoff, not an official roster ranking.",
  },
  {
    id: "steam-expert-tips",
    title: "Expert Tips?",
    publisher: "Steam Community players",
    url: "https://steamcommunity.com/app/2075800/discussions/0/590687864233346675/",
    kind: "community",
    checkedAt: "2026-08-31",
    note: "Player discussion showing that weapon value changes with movement, difficulty, mods and squad role; not treated as consensus.",
  },
  {
    id: "reddit-beginner-friendly",
    title: "Will This Game Be Beginner Friendly?",
    publisher: "r/ZeroCompany",
    url: "https://www.reddit.com/r/ZeroCompany/comments/1vycfob/will_this_game_be_beginner_friendly/",
    kind: "community",
    checkedAt: "2026-08-31",
    note: "Pre-launch and launch-window player perspectives on difficulty, pacing and learning the tactics format; anecdotal only.",
  },
  {
    id: "epic-operators",
    title: "Best Builds for Each Operator",
    publisher: "Epic Games Store",
    url: "https://store.epicgames.com/news/star-wars-zero-company-guide-best-builds-for-each-operator",
    kind: "press",
    checkedAt: "2026-09-01",
    note: "Launch-build companion recruitment, unique Talent and starting-Specialization observations; used as a labeled gameplay cross-check, not as official canon.",
  },
  {
    id: "reddit-bond-strategies",
    title: "Bond Strategies",
    publisher: "r/ZeroCompany",
    url: "https://www.reddit.com/r/ZeroCompany/comments/1w2lngy/bond_strategies/",
    kind: "community",
    checkedAt: "2026-09-01",
    note: "Small, self-selected launch discussion about rotating Operators and building Bonds; exact XP values and optimal routes are not treated as settled facts.",
  },
  {
    id: "reddit-roster-rotation",
    title: "What Is the Point of a Big Roster?",
    publisher: "r/ZeroCompany",
    url: "https://www.reddit.com/r/ZeroCompany/comments/1w0urml/whats_the_point_of_having_a_big_roster_if_you_can/",
    kind: "community",
    checkedAt: "2026-09-01",
    note: "Player debate over a fixed four-Operator squad versus rotation for mission roles, Injuries and Bonds; anecdotal and patch-sensitive.",
  },
  {
    id: "reddit-weapons-specializations",
    title: "Best Weapons for Each Specialization?",
    publisher: "r/ZeroCompany",
    url: "https://www.reddit.com/r/ZeroCompany/comments/1w1owpo/best_weapons_for_each_specialization/",
    kind: "community",
    checkedAt: "2026-09-01",
    note: "Launch discussion comparing Pistol, Rifle, Repeater and Longarm across Specializations; opinions conflict and are not treated as a settled tier list.",
  },
  {
    id: "reddit-repeater-debate",
    title: "Suggested Change to Repeaters",
    publisher: "r/ZeroCompany",
    url: "https://www.reddit.com/r/ZeroCompany/comments/1w2cnte/suggested_change_to_repeaters/",
    kind: "community",
    checkedAt: "2026-09-01",
    note: "Player examples both favoring and rejecting Repeater loadouts; useful for exposing map, AP and build dependencies rather than naming one winner.",
  },
  {
    id: "reddit-difficulty-psa",
    title: "Difficulty PSA for Genre Players",
    publisher: "r/ZeroCompany",
    url: "https://www.reddit.com/r/ZeroCompany/comments/1w08a8h/difficulty_psa_if_you_have_played_the_genre_play/",
    kind: "community",
    checkedAt: "2026-09-01",
    note: "Launch discussion comparing Hard and Expert for experienced tactics players; self-selected experiences, not an official difficulty prescription.",
  },
  {
    id: "reddit-difficulty-question",
    title: "How Is the Difficulty?",
    publisher: "r/ZeroCompany",
    url: "https://www.reddit.com/r/ZeroCompany/comments/1w0gl3x/how_is_the_difficulty/",
    kind: "community",
    checkedAt: "2026-09-01",
    note: "Players compare Normal with prior XCOM experience and disagree about when difficulty rises; used to frame player profiles, not hidden modifiers.",
  },
  {
    id: "reddit-permadeath-threat",
    title: "Permadeath Feels Nonexistent",
    publisher: "r/ZeroCompany",
    url: "https://www.reddit.com/r/ZeroCompany/comments/1w2v9g1/permadeath_feels_non_existent/",
    kind: "community",
    checkedAt: "2026-09-01",
    note: "Expert/Beskar player reports about perceived Permadeath pressure; anecdotal evidence of repeated demand, not a universal difficulty finding.",
  },
];

export const sourceById = new Map(sources.map((source) => [source.id, source]));

export function resolveSources(ids: string[]): Source[] {
  return ids.map((id) => {
    const source = sourceById.get(id);
    if (!source) throw new Error(`Unknown source id: ${id}`);
    return source;
  });
}
